### PR TITLE
Fix CPU usage 100%

### PR DESCRIPTION
**Pull request by yikben-wong-dx**
### Description

- use omp_set_num_threads to limit number of threads allowed to be used

### Motivation and Context

- Cloth simulation used 100% of CPU Power

### How Has This Been Tested?

This test uses the E2E setup in [caisson_ros_pkg](https://github.com/DeepX-inc/caisson_ros_pkg/blob/main/docs/E2E.md). Please make sure you update the caisson_ros_pkg repo and Talos repo.
1. Before the changes
```bash
# Command in server
docker-compose -f ~/caisson_ws/repos/caisson_ros_pkg/docker/system/tsukuba.yml pull
docker-compose -f ~/caisson_ws/repos/caisson_ros_pkg/docker/system/tsukuba.yml up -d
. ~/caisson_ws/repos/caisson_ros_pkg/docker/system/scripts/tsukuba_simulation.bash

# Press Enter for all the window in tmux
```
```
# Command in 6082 Simulator VNC
ros2 launch oliver_ros_interface techfarm_caisson_launch.py rviz:=False
```
```
# Another Terminal in server
htop
```
The htop should show all CPU at close to 100%.
Please Ctrl + C all the windows in tmux only.

Screen Shot 2022-12-27 at 12 58 48

2. Apply the changes
```
# Terminal in server
docker exec -it system /bin/bash
cd /home/docker/base
rm -rf CSF
git clone -b fix/all-cpu-100% git@github.com:DeepX-inc/CSF.git
mkdir -p CSF/build && cd CSF/build \
  && cmake -DBUILD_SHARED_LIBS=ON .. && make -j$(nproc) && make install -j$(nproc) && make clean

# Close terminal
```

3. After the changes
- Please go to the tmux terminal and use the all 4 previous commands in windows to start the system.
- The htop should show normal CPU usage.
- Use GeoViz and Simulation to check whether the height map is working.

Screen Shot 2022-12-27 at 12 59 29

### Checklist

- [x] Have you filled the sections above?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same GitHub Issues/ClickUp Task(s)?
- [x] Have you documented the changes in GitHub Issues and/or ClickUp Task(s) related to this Pull Request?
- [x] Have you added labels, where appropriate, to this Pull Request?

### CODE REVIEW

**Comment by yikben-wong-dx** [comment]
The number of thread (6) does not contain any meaning. Please feel free to change it.

**Comment by matias-pavez-dx** [comment]
I think it is okay as long as the heightmap or acceptance test results are not affected.

I guess this is for the perception team to decide.

**Comment by Apurrvv** [comment]
Yes, 6 is okay. I don't see a way to make this an argument but we one perception side will make a note of the value.

We need to make a change here also - https://github.com/DeepX-inc/caisson_ros_pkg/blob/43b38b90c8577788d07c38c77ef974a4980a6d35/docker/system/base.Dockerfile#L72

I will create a PR.

**Review by Apurrvv — APPROVED** [review]
LGTM, We will make a note. NUM_THREAD is set to 6 in CSF.

**Comment by matias-pavez-dx** [comment]
@Apurrvv 

> Yes, 6 is okay. I don't see a way to make this an argument but we one perception side will make a note of the value.

These are some ways to set the argument from outside:
- Modify the library to allow such configuration (e.g. through function setter, constructor, ...).
- [Use compile options.](https://cmake.org/cmake/help/latest/command/add_compile_options.html).

Anyways, this does not seem like an urgent concern.

**Comment by Apurrvv** [comment]
> @Apurrvv
> 
> > Yes, 6 is okay. I don't see a way to make this an argument but we one perception side will make a note of the value.
> 
> These are some ways to set the argument from outside:
> 
> * Modify the library to allow such configuration (e.g. through function setter, constructor, ...).
> * [Use compile options.](https://cmake.org/cmake/help/latest/command/add_compile_options.html).
> 
> Anyways, this does not seem like an urgent concern.

I see, Got it. I will create an issue for now and create a PR in the future. 
I don't see an option for creating an issue is it disabled by any chance?

**Pull request merged**
